-- 
-- Struttura della tabella `atleta`
-- 

CREATE TABLE `atleta` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `COGNOME` varchar(100) NOT NULL,
  `SESSO` varchar(1) NOT NULL,
  `DATA_NASCITA` date NOT NULL,
  `DATA_TESSERAMENTO` date NOT NULL DEFAULT '0000-00-00',
  `CODICE_FIDAL` varchar(10) NOT NULL,
  `COMUNE_RESIDENZA` varchar(50) DEFAULT NULL,
  `PROVINCIA_RESIDENZA` varchar(2) DEFAULT NULL,
  `INDIRIZZO_RESIDENZA` varchar(100) DEFAULT NULL,
  `TELEFONO` varchar(10) DEFAULT NULL,
  `CELLULARE` varchar(10) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `TAGLIA` varchar(10) DEFAULT NULL,
  `CONSENSO_DATI_PERSONALI` varchar(1) DEFAULT NULL,
  `CREATED` datetime DEFAULT NULL,
  `MODIFIED` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOME_COGNOME_SESSO_DATA_NASCITA` (`NOME`,`COGNOME`,`SESSO`,`DATA_NASCITA`)
) ENGINE=MyISAM AUTO_INCREMENT=179 DEFAULT CHARSET=latin1 AUTO_INCREMENT=179 ;
