-- 
-- Struttura della tabella `gara`
-- 

CREATE TABLE `gara` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CODICE` varchar(15) NOT NULL,
  `NOME` varchar(200) NOT NULL,
  `CAMPIONATO` varchar(255) DEFAULT NULL,
  `LOCALITA` varchar(200) NOT NULL,
  `DATA` date NOT NULL,
  `NOSTRA` varchar(1) NOT NULL DEFAULT 'N',
  `ID_STAGIONE` int(11) DEFAULT NULL,
  `ID_TIPOLOGIA_GARA` int(11) NOT NULL DEFAULT '1',
  `CREATED` datetime NOT NULL,
  `MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOME_CAMPIONATO_LOCALITA_DATA` (`NOME`,`CAMPIONATO`,`LOCALITA`,`DATA`)
) ENGINE=MyISAM AUTO_INCREMENT=276 DEFAULT CHARSET=latin1 AUTO_INCREMENT=276 ;
