-- 
-- Struttura della tabella `preiscrizioni`
-- 

CREATE TABLE `preiscrizioni` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOME_ATLETA` varchar(255) NOT NULL,
  `COGNOME_ATLETA` varchar(255) NOT NULL,
  `SESSO_ATLETA` varchar(1) NOT NULL,
  `ANNO_NASCITA_ATLETA` varchar(4) DEFAULT NULL,
  `CATEGORIA_ATLETA` varchar(10) DEFAULT NULL,
  `CODICE_FIDAL_ATLETA` varchar(10) DEFAULT NULL,
  `NOME_SOCIETA` varchar(255) NOT NULL,
  `CODICE_SOCIETA` varchar(5) DEFAULT NULL,
  `EMAIL_ATLETA` varchar(255) DEFAULT NULL,
  `ID_GARA` bigint(20) NOT NULL,
  `CODICE_GARA` varchar(15) NOT NULL,
  `CREATED` datetime DEFAULT NULL,
  `MODIFIED` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_ATLETA_GARA` (`NOME_ATLETA`,`COGNOME_ATLETA`,`SESSO_ATLETA`,`ANNO_NASCITA_ATLETA`,`CODICE_FIDAL_ATLETA`,`ID_GARA`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;
