-- 
-- Struttura della tabella `presenza`
-- 

CREATE TABLE `presenza` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_ATLETA` bigint(20) NOT NULL,
  `ID_GARA` bigint(20) NOT NULL,
  `ID_STAGIONE` bigint(20) NOT NULL,
  `CREATED` datetime NOT NULL,
  `MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_ATLETA_ID_GARA_ID_STAGIONE` (`ID_ATLETA`,`ID_GARA`,`ID_STAGIONE`),
  KEY `FK_ATLETA` (`ID_ATLETA`),
  KEY `FK_GARA` (`ID_GARA`),
  KEY `FK_STAGIONE` (`ID_STAGIONE`)
) ENGINE=MyISAM AUTO_INCREMENT=838 DEFAULT CHARSET=latin1 AUTO_INCREMENT=838 ;
